### ISSUE TITLE
Carbon Plugin Not Stable

### ISSUE THREAD

**Issue by keyiflerolsun** [SkuzzyxD/TelePyroBot#9]
carbon plugin comes as a single line

![IMG_20200901_004140_545](https://user-images.githubusercontent.com/57468649/91771608-f183a580-ebeb-11ea-9b45-d827f5565198.jpg)

green pic your code,
pink pic other bot

**Comment by keyiflerolsun** [comment]
i found how to fix it

```
import urllib

json['code'] = urllib.parse.quote(message.text)
```

**Comment by Divkix** [comment]
I'll add this
